-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 11:01:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `DealerStat` ;
-- -----------------------------------------------------
-- Schema userbanklist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `userbanklist` ;

-- -----------------------------------------------------
-- Schema userbanklist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userbanklist` DEFAULT CHARACTER SET utf8 ;
USE `userbanklist` ;

-- -----------------------------------------------------
-- Table `userbanklist`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userbanklist`.`user` ;

CREATE TABLE IF NOT EXISTS `userbanklist`.`user` (
  `userid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userbanklist`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userbanklist`.`account` ;

CREATE TABLE IF NOT EXISTS `userbanklist`.`account` (
  `accountid` INT NOT NULL,
  `account` INT NULL,
  `userid` INT NOT NULL,
  PRIMARY KEY (`accountid`),
  INDEX `fk_account_user_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_account_user`
    FOREIGN KEY (`userid`)
    REFERENCES `userbanklist`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO user  (userid, name, surname)
VALUES (1, 'Jack', 'Wolf');

INSERT INTO user  (userid, name, surname)
VALUES (2, 'Joe', 'Sith');

INSERT INTO user  (userid, name, surname)
VALUES (3, 'Bob', 'Gale');

INSERT INTO user  (userid, name, surname)
VALUES (4, 'John', 'Wolf');

INSERT INTO user  (userid, name, surname)
VALUES (5, 'Rob', 'Walker');

INSERT INTO user  (userid, name, surname)
VALUES (6, 'Jack', 'Scar');

INSERT INTO user  (userid, name, surname)
VALUES (7, 'Sam', 'Dude');

INSERT INTO user  (userid, name, surname)
VALUES (8, 'Brian', 'March');

INSERT INTO user  (userid, name, surname)
VALUES (9, 'Will', 'Nye');

INSERT INTO user  (userid, name, surname)
VALUES (10, 'Nick', 'Finger');

INSERT INTO account  (accountid, account, userid)
VALUES (1, 60, 3);

INSERT INTO account  (accountid, account, userid)
VALUES (2, 30, 5);

INSERT INTO account  (accountid, account, userid)
VALUES (3, 60, 3);

INSERT INTO account  (accountid, account, userid)
VALUES (4, 60, 3);

INSERT INTO account  (accountid, account, userid)
VALUES (5, 60, 3);

INSERT INTO account  (accountid, account, userid)
VALUES (6, 60, 7);

INSERT INTO account  (accountid, account, userid)
VALUES (7, 60, 4);

INSERT INTO account  (accountid, account, userid)
VALUES (8, 60, 3);

INSERT INTO account  (accountid, account, userid)
VALUES (9, 20, 2);

INSERT INTO account  (accountid, account, userid)
VALUES (10, 100, 9);

